"""Delete tests ... cascade on deleting paciente

Revision ID: 0bffb6a89119
Revises: 64c773253631
Create Date: 2023-10-18 10:51:30.891113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bffb6a89119'
down_revision = '64c773253631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acciones_test_medico_ibfk_1', 'acciones_test_medico', type_='foreignkey')
    op.drop_constraint('acciones_test_medico_ibfk_2', 'acciones_test_medico', type_='foreignkey')
    op.create_foreign_key(None, 'acciones_test_medico', 'test', ['num_test', 'id_paciente'], ['num_test', 'id_paciente'], ondelete='CASCADE')
    op.create_foreign_key(None, 'acciones_test_medico', 'users', ['id_medico'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pacientes_asociados_ibfk_2', 'pacientes_asociados', type_='foreignkey')
    op.drop_constraint('pacientes_asociados_ibfk_1', 'pacientes_asociados', type_='foreignkey')
    op.create_foreign_key(None, 'pacientes_asociados', 'users', ['id_paciente'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pacientes_asociados', 'users', ['id_medico'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_ibfk_1', 'test', type_='foreignkey')
    op.create_foreign_key(None, 'test', 'users', ['id_paciente'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_unit_ibfk_1', 'test_unit', type_='foreignkey')
    op.create_foreign_key(None, 'test_unit', 'test', ['num_test', 'id_paciente'], ['num_test', 'id_paciente'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_unit', type_='foreignkey')
    op.create_foreign_key('test_unit_ibfk_1', 'test_unit', 'test', ['num_test', 'id_paciente'], ['num_test', 'id_paciente'])
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_foreign_key('test_ibfk_1', 'test', 'users', ['id_paciente'], ['id'])
    op.drop_constraint(None, 'pacientes_asociados', type_='foreignkey')
    op.drop_constraint(None, 'pacientes_asociados', type_='foreignkey')
    op.create_foreign_key('pacientes_asociados_ibfk_1', 'pacientes_asociados', 'users', ['id_paciente'], ['id'])
    op.create_foreign_key('pacientes_asociados_ibfk_2', 'pacientes_asociados', 'users', ['id_medico'], ['id'])
    op.drop_constraint(None, 'acciones_test_medico', type_='foreignkey')
    op.drop_constraint(None, 'acciones_test_medico', type_='foreignkey')
    op.create_foreign_key('acciones_test_medico_ibfk_2', 'acciones_test_medico', 'users', ['id_medico'], ['id'])
    op.create_foreign_key('acciones_test_medico_ibfk_1', 'acciones_test_medico', 'test', ['num_test', 'id_paciente'], ['num_test', 'id_paciente'])
    # ### end Alembic commands ###
