"""cambiar modelo

Revision ID: 462e43afeebe
Revises: 
Create Date: 2023-08-31 11:43:26.507478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '462e43afeebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('probabilidad_caida', sa.Float(), nullable=True))
    op.drop_column('test', 'bow')
    op.drop_column('test', 'fall_to_left')
    op.drop_column('test', 'falling_backward')
    op.drop_column('test', 'standing')
    op.drop_column('test', 'sleep')
    op.drop_column('test', 'sitting')
    op.drop_column('test', 'fall_to_right')
    op.drop_column('test', 'falling_forward')
    op.drop_column('test', 'idle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('idle', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('falling_forward', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('fall_to_right', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('sitting', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('sleep', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('standing', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('falling_backward', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('fall_to_left', mysql.FLOAT(), nullable=True))
    op.add_column('test', sa.Column('bow', mysql.FLOAT(), nullable=True))
    op.drop_column('test', 'probabilidad_caida')
    # ### end Alembic commands ###
