"""apellidos y medico que ha hecho el test

Revision ID: 64c773253631
Revises: 7b4125408783
Create Date: 2023-09-26 08:45:23.706356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c773253631'
down_revision = '7b4125408783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('id_medico', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'users', ['id_medico'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('apellidos', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'apellidos')
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'id_medico')
    # ### end Alembic commands ###
