"""BLOB

Revision ID: 9c592121801f
Revises: 462e43afeebe
Create Date: 2023-09-01 10:37:19.911700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c592121801f'
down_revision = '462e43afeebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'data')
    # ### end Alembic commands ###
